# DeepEval Configuration for AetheroOS Agent Stack

version: "1.0"
environment: "production"

# Core Evaluation Settings
core_settings:
  parallel_evaluations: true
  cache_results: true
  logging_level: "detailed"
  timeout_seconds: 30

# Evaluation Criteria
evaluation_criteria:
  accuracy:
    weight: 0.35
    thresholds:
      high: 0.85
      medium: 0.70
      low: 0.50
    metrics:
      - name: "factual_correctness"
        weight: 0.4
      - name: "completeness"
        weight: 0.3
      - name: "relevance"
        weight: 0.3

  consistency:
    weight: 0.25
    thresholds:
      high: 0.90
      medium: 0.75
      low: 0.60
    metrics:
      - name: "internal_consistency"
        weight: 0.5
      - name: "cross_reference_validity"
        weight: 0.3
      - name: "temporal_consistency"
        weight: 0.2

  ethical_compliance:
    weight: 0.20
    thresholds:
      high: 0.95
      medium: 0.85
      low: 0.70
    metrics:
      - name: "bias_detection"
        weight: 0.4
      - name: "fairness_score"
        weight: 0.3
      - name: "transparency_level"
        weight: 0.3

  performance:
    weight: 0.20
    thresholds:
      high: 0.80
      medium: 0.65
      low: 0.50
    metrics:
      - name: "response_time"
        weight: 0.3
      - name: "resource_efficiency"
        weight: 0.3
      - name: "output_quality"
        weight: 0.4

# Agent-Specific Evaluation Rules
agent_rules:
  planner_agent:
    required_criteria:
      - "task_decomposition_quality"
      - "priority_assignment_accuracy"
      - "resource_allocation_efficiency"
    custom_thresholds:
      accuracy: 0.90
      consistency: 0.85

  scout_agent:
    required_criteria:
      - "source_reliability"
      - "information_relevance"
      - "search_coverage"
    custom_thresholds:
      accuracy: 0.85
      completeness: 0.80

  analyst_agent:
    required_criteria:
      - "analysis_depth"
      - "critical_thinking"
      - "synthesis_quality"
    custom_thresholds:
      accuracy: 0.90
      ethical_compliance: 0.95

  generator_agent:
    required_criteria:
      - "code_quality"
      - "documentation_completeness"
      - "artifact_usability"
    custom_thresholds:
      accuracy: 0.85
      performance: 0.80

  synthesis_agent:
    required_criteria:
      - "synthesis_coherence"
      - "conclusion_validity"
      - "recommendation_quality"
    custom_thresholds:
      accuracy: 0.90
      consistency: 0.90

  reflection_agent:
    required_criteria:
      - "evaluation_accuracy"
      - "suggestion_relevance"
      - "improvement_impact"
    custom_thresholds:
      accuracy: 0.95
      ethical_compliance: 0.95

# Integration Settings
integration:
  aethero_mem:
    enabled: true
    sync_interval_seconds: 60
    storage_policy:
      retain_days: 30
      compression: true

  monitoring:
    enabled: true
    metrics_export:
      prometheus: true
      grafana: true
    alert_thresholds:
      critical_failure: 0.5
      warning: 0.7

  reporting:
    formats:
      - json
      - markdown
    automated_reports:
      enabled: true
      frequency: "daily"
      recipients:
        - "system_admin"
        - "quality_team"

# Validation Schemas
validation_schemas:
  output_schema:
    type: "object"
    required:
      - "metrics"
      - "findings"
      - "suggestions"
    properties:
      metrics:
        type: "object"
        required:
          - "accuracy"
          - "consistency"
          - "ethical_compliance"
          - "performance"
      findings:
        type: "array"
        items:
          type: "string"
      suggestions:
        type: "array"
        items:
          type: "string"

# Error Handling
error_handling:
  retry_attempts: 3
  backoff_factor: 2
  max_backoff_seconds: 30
  failure_policy: "fail_fast"

# Performance Optimization
optimization:
  caching:
    enabled: true
    ttl_seconds: 3600
  batching:
    enabled: true
    max_batch_size: 10
    max_wait_ms: 100
